version: "3.3"
services:
  CsvServer:
    #environment:
    #  - CSVSERVER_BORDER=
    env_file:
      - ./env
    ports:
      - "9393:9300"
    volumes:
      - ./inputFile:/csvserver/inputdata
    image: "infracloudio/csvserver:latest"

  Prometheus:
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    image: "prom/prometheus:v2.22.0"
